stages:
  - build
  - test
  #- deploy

variables:
  DOCKER_IMAGE: $DOCKER_IMAGE

image: docker:dind

services:
  - docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD 

build:
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

test:
  stage: test
  image: python:3.9-slim
  before_script:
    - pip install -r requirements.txt
    - pip install pytest
  script:
    - pytest test_app.py

# deploy:
#   stage: deploy
#   script:
#     - echo "Deploy stage can be defined here"
#     # Add your deployment scripts here