apiVersion: app/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicaset: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      -name: myapp
      image: ran_saadon_portfolio/argocd-app:1.0
      ports:
      - containerPort:8081