name: CI

on: [push, pull_request]

jobs:
      
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest test_app.py

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
      
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE }} .
          docker push ${{ secrets.DOCKER_IMAGE }}

  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install bandit

      - name: Print Bandit version
        run: bandit --version

      - name: Run Bandit to check for security issues (debug)
        run: |
          bandit -r . -f json -o bandit-report.json -v

      - name: Print Bandit report
        run: |
          cat bandit-report.json || true

      - name: Fail if Bandit found issues
        run: |
          if grep -q '"issues": []' bandit-report.json; then
            echo "Bandit found no issues."
            exit 0
          else
            echo "Bandit found issues."
            exit 1
          fi


  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install latest Snyk CLI
        run: npm install -g snyk@latest

      - name: Run Snyk to check for vulnerabilities (debug mode)
        run: DEBUG=*snyk* snyk test --json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Print Snyk test results
        run: snyk test --json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}



